Repository garg3133/JagratiWebApp, pull requests merged in 2021-02, with the labels that each got.

#88 Added github action
  .github/workflows/greetings.yml
Labels: user=Aayush-hub:score=25

#96 Replace `Change Password` with `Dashboard` on header #38
  templates/snippets/header.html
Labels: user=SwarupKharul:score=25

#104 Added Flake8 Linter
  .github/linters/.flake8.yml
  .github/workflows/python_lint.yml
Labels: user=vybhav72954:score=25
