Repository garg3133/JagratiWebApp, pull requests merged in 2021-01, with the labels that each got.

#49 CONTRIBUTING AND CODE OF CONDUCT FILE
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: SWOC 2021, medium

#51 Added a gender field in Student model #35
  apps/students/models.py
Labels: Beginner, SWOC 2021

#61 issue #47
  apps/students/urls.py
  apps/students/views.py
  templates/students/add_new_student.html
Labels: SWOC 2021, hard

#68 Optimized Images use for fast loading of site.
  static/home/images/01.jpg
  static/home/images/04.jpg
  static/home/images/close.png
  static/home/images/menu.png
  static/home/logo.jpg
  static/home/logo.png
  static/icon/lock.gif
  static/icon/mail-sent.gif
  static/icon/tick.gif
  static/logo.png
  static/vendor/webfonts/fa-brands-400.svg
  static/vendor/webfonts/fa-regular-400.svg
  static/vendor/webfonts/fa-solid-900.svg
Labels: SWOC 2021, easy
